apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f Documents/dev/SD2023/docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: search-service
  namespace: sge
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f Documents/dev/SD2023/docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  key: APP_DEBUG
                  name: app--env
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  key: APP_ENV
                  name: app--env
            - name: APP_KEY
              valueFrom:
                configMapKeyRef:
                  key: APP_KEY
                  name: app--env
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  key: APP_NAME
                  name: app--env
            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  key: APP_URL
                  name: app--env
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  key: AWS_ACCESS_KEY_ID
                  name: app--env
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: AWS_BUCKET
                  name: app--env
            - name: AWS_DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  key: AWS_DEFAULT_REGION
                  name: app--env
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: AWS_SECRET_ACCESS_KEY
                  name: app--env
            - name: AWS_USE_PATH_STYLE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: AWS_USE_PATH_STYLE_ENDPOINT
                  name: app--env
            - name: BROADCAST_DRIVER
              valueFrom:
                configMapKeyRef:
                  key: BROADCAST_DRIVER
                  name: app--env
            - name: CACHE_DRIVER
              valueFrom:
                configMapKeyRef:
                  key: CACHE_DRIVER
                  name: app--env
            - name: DB_CONNECTION
              valueFrom:
                configMapKeyRef:
                  key: DB_CONNECTION
                  name: app--env
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: DB_DATABASE
                  name: app--env
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: app--env
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: app--env
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: app--env
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: DB_USERNAME
                  name: app--env
            - name: FILESYSTEM_DISK
              valueFrom:
                configMapKeyRef:
                  key: FILESYSTEM_DISK
                  name: app--env
            - name: LOG_CHANNEL
              valueFrom:
                configMapKeyRef:
                  key: LOG_CHANNEL
                  name: app--env
            - name: LOG_DEPRECATIONS_CHANNEL
              valueFrom:
                configMapKeyRef:
                  key: LOG_DEPRECATIONS_CHANNEL
                  name: app--env
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: LOG_LEVEL
                  name: app--env
            - name: MAIL_ENCRYPTION
              valueFrom:
                configMapKeyRef:
                  key: MAIL_ENCRYPTION
                  name: app--env
            - name: MAIL_FROM_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: MAIL_FROM_ADDRESS
                  name: app--env
            - name: MAIL_FROM_NAME
              valueFrom:
                configMapKeyRef:
                  key: MAIL_FROM_NAME
                  name: app--env
            - name: MAIL_HOST
              valueFrom:
                configMapKeyRef:
                  key: MAIL_HOST
                  name: app--env
            - name: MAIL_MAILER
              valueFrom:
                configMapKeyRef:
                  key: MAIL_MAILER
                  name: app--env
            - name: MAIL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MAIL_PASSWORD
                  name: app--env
            - name: MAIL_PORT
              valueFrom:
                configMapKeyRef:
                  key: MAIL_PORT
                  name: app--env
            - name: MAIL_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: MAIL_USERNAME
                  name: app--env
            - name: MEMCACHED_HOST
              valueFrom:
                configMapKeyRef:
                  key: MEMCACHED_HOST
                  name: app--env
            - name: PUSHER_APP_CLUSTER
              valueFrom:
                configMapKeyRef:
                  key: PUSHER_APP_CLUSTER
                  name: app--env
            - name: PUSHER_APP_ID
              valueFrom:
                configMapKeyRef:
                  key: PUSHER_APP_ID
                  name: app--env
            - name: PUSHER_APP_KEY
              valueFrom:
                configMapKeyRef:
                  key: PUSHER_APP_KEY
                  name: app--env
            - name: PUSHER_APP_SECRET
              valueFrom:
                configMapKeyRef:
                  key: PUSHER_APP_SECRET
                  name: app--env
            - name: PUSHER_HOST
              valueFrom:
                configMapKeyRef:
                  key: PUSHER_HOST
                  name: app--env
            - name: PUSHER_PORT
              valueFrom:
                configMapKeyRef:
                  key: PUSHER_PORT
                  name: app--env
            - name: PUSHER_SCHEME
              valueFrom:
                configMapKeyRef:
                  key: PUSHER_SCHEME
                  name: app--env
            - name: QUEUE_CONNECTION
              valueFrom:
                configMapKeyRef:
                  key: QUEUE_CONNECTION
                  name: app--env
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  key: REDIS_HOST
                  name: app--env
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: REDIS_PASSWORD
                  name: app--env
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  key: REDIS_PORT
                  name: app--env
            - name: SESSION_DRIVER
              valueFrom:
                configMapKeyRef:
                  key: SESSION_DRIVER
                  name: app--env
            - name: SESSION_LIFETIME
              valueFrom:
                configMapKeyRef:
                  key: SESSION_LIFETIME
                  name: app--env
            - name: VITE_APP_NAME
              valueFrom:
                configMapKeyRef:
                  key: VITE_APP_NAME
                  name: app--env
            - name: VITE_PUSHER_APP_CLUSTER
              valueFrom:
                configMapKeyRef:
                  key: VITE_PUSHER_APP_CLUSTER
                  name: app--env
            - name: VITE_PUSHER_APP_KEY
              valueFrom:
                configMapKeyRef:
                  key: VITE_PUSHER_APP_KEY
                  name: app--env
            - name: VITE_PUSHER_HOST
              valueFrom:
                configMapKeyRef:
                  key: VITE_PUSHER_HOST
                  name: app--env
            - name: VITE_PUSHER_PORT
              valueFrom:
                configMapKeyRef:
                  key: VITE_PUSHER_PORT
                  name: app--env
            - name: VITE_PUSHER_SCHEME
              valueFrom:
                configMapKeyRef:
                  key: VITE_PUSHER_SCHEME
                  name: app--env
          image: claysless/app:1.0.1
          name: app
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
