version: "3.7"

services:
  app:
    container_name: app
    image: claysless/app:1.0.1
    build: app/
    ports:
      - "8000:8000"
    env_file:
      - app/.env
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sd23
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysqlvol:/var/lib/mysql
