apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: search-service
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30008
    protocol: TCP
